# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherTest
  pod 'SDWebImage', '~> 4.0'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'AFNetworking', '~> 1.3.1'
  
  target 'WeatherTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WeatherTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
